/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    accounts: AccountAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    documentation: Documentation;
    posts: Post;
    accounts: Account;
    packages: Package;
    'package-versions': PackageVersion;
    listings: Listing;
    namespaces: Namespace;
    products: Product;
    entitlements: Entitlement;
    publishers: Publisher;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    documentation: DocumentationSelect<false> | DocumentationSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    'package-versions': PackageVersionsSelect<false> | PackageVersionsSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    namespaces: NamespacesSelect<false> | NamespacesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    entitlements: EntitlementsSelect<false> | EntitlementsSelect<true>;
    publishers: PublishersSelect<false> | PublishersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-navigation': SiteNavigation;
  };
  globalsSelect: {
    'site-navigation': SiteNavigationSelect<false> | SiteNavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Account;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AccountAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            link?: {
              label?: string | null;
              url?: string | null;
            };
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            heading: string;
            text?: string | null;
            buttonLabel?: string | null;
            buttonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentation".
 */
export interface Documentation {
  id: number;
  title: string;
  slug: string;
  /**
   * Choose a parent document to create a nested documentation structure.
   */
  parent?: (number | null) | Documentation;
  status: 'draft' | 'published';
  order: number;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  /**
   * A short summary used on post listings and previews.
   */
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * Categories such as Releases, Development, Guides, or Announcements.
   */
  categories?: string[] | null;
  /**
   * Add keywords that help organize and filter posts.
   */
  tags?: string[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Public username used across the Phestus marketplace.
   */
  username?: string | null;
  /**
   * Public name displayed on the Phestus marketplace.
   */
  displayName?: string | null;
  website?: string | null;
  phone?: string | null;
  accountType: 'personal' | 'seller';
  /**
   * Whether this account can publish marketplace listings.
   */
  isSeller?: boolean | null;
  company?: string | null;
  status: 'active' | 'underReview' | 'suspended';
  /**
   * Internal notes about this customer.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'accounts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  name: string;
  slug: string;
  namespace: number | Namespace;
  publisher: number | Publisher;
  type: 'module' | 'provider' | 'plugin' | 'service' | 'other';
  description?: string | null;
  readme?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  repository?: string | null;
  homepage?: string | null;
  documentationUrl?: string | null;
  license?: string | null;
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  visibility: 'public' | 'unlisted' | 'private';
  access: 'free' | 'paid' | 'restricted';
  status: 'draft' | 'pending' | 'published' | 'suspended' | 'deprecated';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "namespaces".
 */
export interface Namespace {
  id: number;
  name: string;
  displayName: string;
  slug: string;
  type: 'official' | 'organization' | 'individual';
  publisher: number | Publisher;
  allowPublishing?: boolean | null;
  requireApproval?: boolean | null;
  packageLimit?: number | null;
  description?: string | null;
  logo?: (number | null) | Media;
  website?: string | null;
  verified?: boolean | null;
  verifiedAt?: string | null;
  verifiedBy?: (number | null) | User;
  status: 'active' | 'suspended' | 'reserved';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishers".
 */
export interface Publisher {
  id: number;
  name: string;
  slug: string;
  displayName: string;
  type: 'individual' | 'organization' | 'official';
  owner: number | User;
  members?:
    | {
        user: number | User;
        role: 'owner' | 'admin' | 'maintainer' | 'developer' | 'viewer';
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  logo?: (number | null) | Media;
  website?: string | null;
  github?: string | null;
  twitter?: string | null;
  verified?: boolean | null;
  verifiedAt?: string | null;
  verifiedBy?: (number | null) | User;
  status: 'pending' | 'active' | 'suspended' | 'disabled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-versions".
 */
export interface PackageVersion {
  id: number;
  package: number | Package;
  version: string;
  status: 'draft' | 'pending' | 'published' | 'deprecated' | 'yanked';
  dependencies?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  peerDependencies?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  optionalDependencies?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  engines?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  packageJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  tarball?: (number | null) | Media;
  integrity?: string | null;
  shasum?: string | null;
  size?: number | null;
  changelog?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  releaseNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  publishedBy?: (number | null) | Publisher;
  registryPublished?: boolean | null;
  registryPackageName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  title: string;
  slug: string;
  package: number | Package;
  publisher: number | Publisher;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon?: (number | null) | Media;
  banner?: (number | null) | Media;
  screenshots?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  category?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  verified?: boolean | null;
  official?: boolean | null;
  order?: number | null;
  repositoryUrl?: string | null;
  documentationUrl?: string | null;
  supportUrl?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaImage?: (number | null) | Media;
  status: 'draft' | 'review' | 'published' | 'hidden';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type: 'package' | 'bundle' | 'subscription' | 'license' | 'other';
  packages: (number | Package)[];
  accessType: 'permanent' | 'subscription' | 'time-limited';
  price: number;
  currency: string;
  billing: 'free' | 'one_time' | 'monthly' | 'yearly';
  listing?: (number | null) | Listing;
  featured?: boolean | null;
  stripeProductId?: string | null;
  stripePriceId?: string | null;
  status: 'draft' | 'active' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements".
 */
export interface Entitlement {
  id: number;
  user: number | User;
  package: number | Package;
  product?: (number | null) | Product;
  source: 'purchase' | 'subscription' | 'free' | 'bundle' | 'admin' | 'developer' | 'promotion' | 'trial';
  status: 'active' | 'expired' | 'revoked' | 'suspended';
  startsAt?: string | null;
  expiresAt?: string | null;
  transactionId?: string | null;
  registryAccess?: boolean | null;
  lastRegistryAccess?: string | null;
  registryAccessCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'documentation';
        value: number | Documentation;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'package-versions';
        value: number | PackageVersion;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'namespaces';
        value: number | Namespace;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'entitlements';
        value: number | Entitlement;
      } | null)
    | ({
        relationTo: 'publishers';
        value: number | Publisher;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'accounts';
        value: number | Account;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'accounts';
        value: number | Account;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              image?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              text?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentation_select".
 */
export interface DocumentationSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  status?: T;
  order?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  status?: T;
  publishedAt?: T;
  categories?: T;
  tags?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  username?: T;
  displayName?: T;
  website?: T;
  phone?: T;
  accountType?: T;
  isSeller?: T;
  company?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  namespace?: T;
  publisher?: T;
  type?: T;
  description?: T;
  readme?: T;
  repository?: T;
  homepage?: T;
  documentationUrl?: T;
  license?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  visibility?: T;
  access?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-versions_select".
 */
export interface PackageVersionsSelect<T extends boolean = true> {
  package?: T;
  version?: T;
  status?: T;
  dependencies?: T;
  peerDependencies?: T;
  optionalDependencies?: T;
  engines?: T;
  packageJson?: T;
  tarball?: T;
  integrity?: T;
  shasum?: T;
  size?: T;
  changelog?: T;
  releaseNotes?: T;
  publishedAt?: T;
  publishedBy?: T;
  registryPublished?: T;
  registryPackageName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  package?: T;
  publisher?: T;
  shortDescription?: T;
  description?: T;
  icon?: T;
  banner?: T;
  screenshots?:
    | T
    | {
        image?: T;
        id?: T;
      };
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  verified?: T;
  official?: T;
  order?: T;
  repositoryUrl?: T;
  documentationUrl?: T;
  supportUrl?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "namespaces_select".
 */
export interface NamespacesSelect<T extends boolean = true> {
  name?: T;
  displayName?: T;
  slug?: T;
  type?: T;
  publisher?: T;
  allowPublishing?: T;
  requireApproval?: T;
  packageLimit?: T;
  description?: T;
  logo?: T;
  website?: T;
  verified?: T;
  verifiedAt?: T;
  verifiedBy?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  type?: T;
  packages?: T;
  accessType?: T;
  price?: T;
  currency?: T;
  billing?: T;
  listing?: T;
  featured?: T;
  stripeProductId?: T;
  stripePriceId?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements_select".
 */
export interface EntitlementsSelect<T extends boolean = true> {
  user?: T;
  package?: T;
  product?: T;
  source?: T;
  status?: T;
  startsAt?: T;
  expiresAt?: T;
  transactionId?: T;
  registryAccess?: T;
  lastRegistryAccess?: T;
  registryAccessCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishers_select".
 */
export interface PublishersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  displayName?: T;
  type?: T;
  owner?: T;
  members?:
    | T
    | {
        user?: T;
        role?: T;
        id?: T;
      };
  description?: T;
  logo?: T;
  website?: T;
  github?: T;
  twitter?: T;
  verified?: T;
  verifiedAt?: T;
  verifiedBy?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation".
 */
export interface SiteNavigation {
  id: number;
  header?: {
    logo?: {
      light?: (number | null) | Media;
      dark?: (number | null) | Media;
      alt?: string | null;
    };
    navigation?:
      | {
          label: string;
          location?: ('left' | 'center' | 'right') | null;
          link?: {
            type?: ('internal' | 'external') | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'documentation';
                  value: number | Documentation;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            newTab?: boolean | null;
          };
          /**
           * Add child links to turn this item into a dropdown.
           */
          children?:
            | {
                label: string;
                description?: string | null;
                link?: {
                  type?: ('internal' | 'external') | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: number | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: number | Post;
                      } | null)
                    | ({
                        relationTo: 'documentation';
                        value: number | Documentation;
                      } | null);
                  url?: string | null;
                  newTab?: boolean | null;
                };
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    logo?: {
      light?: (number | null) | Media;
      dark?: (number | null) | Media;
    };
    description?: string | null;
    email?: string | null;
    phone?: string | null;
    columns?:
      | {
          title: string;
          links?:
            | {
                label: string;
                link?: {
                  type?: ('internal' | 'external') | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: number | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: number | Post;
                      } | null)
                    | ({
                        relationTo: 'documentation';
                        value: number | Documentation;
                      } | null);
                  url?: string | null;
                  newTab?: boolean | null;
                };
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    copyright?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation_select".
 */
export interface SiteNavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        logo?:
          | T
          | {
              light?: T;
              dark?: T;
              alt?: T;
            };
        navigation?:
          | T
          | {
              label?: T;
              location?: T;
              link?:
                | T
                | {
                    type?: T;
                    reference?: T;
                    url?: T;
                    newTab?: T;
                  };
              children?:
                | T
                | {
                    label?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          reference?: T;
                          url?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
      };
  footer?:
    | T
    | {
        logo?:
          | T
          | {
              light?: T;
              dark?: T;
            };
        description?: T;
        email?: T;
        phone?: T;
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          reference?: T;
                          url?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}